force-app/main/default/objects/PT_HttpRequest__mdt/PT_HttpRequest__mdt.object-meta.xml
<CustomObject>
    <label>PT_HttpRequest</label>
    <pluralLabel>PT_HttpRequests</pluralLabel>
</CustomObject>

force-app/main/default/objects/PT_HttpRequest__mdt/fields/PT_ActiveMock__c.field-meta.xml
<CustomField>
    <fullName>PT_ActiveMock__c</fullName>
    <label>Active Mock</label>
    <referenceTo>PT_HttpResponseMock__mdt</referenceTo>
    <relationshipLabel>PT_HttpRequests</relationshipLabel>
    <relationshipName>PT_HttpRequests</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/PT_HttpRequest__mdt/fields/PT_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>PT_Endpoint__c</fullName>
    <label>Endpoint</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PT_HttpRequest__mdt/fields/PT_HttpMethod__c.field-meta.xml
<CustomField>
    <fullName>PT_HttpMethod__c</fullName>
    <description>Used to set the HTTP method on the request.</description>
    <label>Http Method</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GET</fullName>
                <default>true</default>
                <label>GET</label>
            </value>
            <value>
                <fullName>POST</fullName>
            </value>
            <value>
                <fullName>PUT</fullName>
            </value>
            <value>
                <fullName>DELETE</fullName>
            </value>
            <value>
                <fullName>HEAD</fullName>
            </value>
            <value>
                <fullName>CONNECT</fullName>
            </value>
            <value>
                <fullName>OPTIONS</fullName>
            </value>
            <value>
                <fullName>TRACE</fullName>
            </value>
            <value>
                <fullName>PATCH</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PT_HttpRequest__mdt/fields/PT_Timeout__c.field-meta.xml
<CustomField>
    <fullName>PT_Timeout__c</fullName>
    <description>Timeout that will be set on the request</description>
    <inlineHelpText>In milliseconds. If left blank it&apos;s set to 10 000ms. Valid range is 1 - 120 000ms</inlineHelpText>
    <label>Timeout</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PT_HttpResponseMock__mdt/PT_HttpResponseMock__mdt.object-meta.xml
<CustomObject>
    <label>PT_HttpResponseMock</label>
    <pluralLabel>PT_HttpResponseMocks</pluralLabel>
</CustomObject>

force-app/main/default/objects/PT_HttpResponseMock__mdt/fields/PT_Body__c.field-meta.xml
<CustomField>
    <fullName>PT_Body__c</fullName>
    <label>Body</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/PT_HttpResponseMock__mdt/fields/PT_StatusCode__c.field-meta.xml
<CustomField>
    <fullName>PT_StatusCode__c</fullName>
    <label>Status Code</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/HttpRequest/PT_HttpRequestConfig.cls
public class PT_HttpRequestConfig implements PT_IHttpRequestConfig {
    @TestVisible
    private PT_HttpRequest__mdt record;

    @TestVisible
    private PT_HttpRequestConfig() {}

    public PT_HttpRequestConfig(String metadataName) {
        record = PT_HttpRequest__mdt.getInstance(metadataName);
        if (record == null) {
            throw new PT_HttpRequestConfigException(
                    PT_HttpRequestConfigException.ExceptionType.NoMdtFound,
                    metadataName);
        }
    }

    public PT_IHttpResponseMock getActiveMock() {
        if (!hasActiveMock()) {
            throw new PT_HttpRequestConfigException(
                    PT_HttpRequestConfigException.ExceptionType.NoMockFound,
                    record.DeveloperName);
        }

        PT_HttpResponseMock__mdt requestMock =
                PT_HttpResponseMock__mdt.getInstance(record.PT_ActiveMock__c);

        return new PT_RuntimeHttpResponseMock(
                Integer.valueOf(requestMock.PT_StatusCode__c),
                requestMock.PT_Body__c);
    }

    public Boolean hasActiveMock() {
        return record.PT_ActiveMock__c != null && inValidContext();
    }

    public Integer getTimeout() {
        return Integer.valueOf(record.PT_Timeout__c);
    }

    public String getEndpoint() {
        return record.PT_Endpoint__c;
    }

    public String getMethod() {
        return record.PT_HttpMethod__c;
    }

    private static Boolean inValidContext() {
        //In tests always respond with native HttpCalloutMock
        return !Test.isRunningTest();
    }
}