force-app/main/default/objects/PT_HttpRequest__mdt/PT_HttpRequest__mdt.object-meta.xml
<CustomObject>
    <label>PT_HttpRequest</label>
    <pluralLabel>PT_HttpRequests</pluralLabel>
</CustomObject>

force-app/main/default/objects/PT_HttpRequest__mdt/fields/PT_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>PT_Endpoint__c</fullName>
    <label>Endpoint</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PT_HttpRequest__mdt/fields/PT_HttpMethod__c.field-meta.xml
<CustomField>
    <fullName>PT_HttpMethod__c</fullName>
    <description>Used to set the HTTP method on the request.</description>
    <label>Http Method</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GET</fullName>
                <default>true</default>
                <label>GET</label>
            </value>
            <value>
                <fullName>POST</fullName>
            </value>
            <value>
                <fullName>PUT</fullName>
            </value>
            <value>
                <fullName>DELETE</fullName>
            </value>
            <value>
                <fullName>HEAD</fullName>
            </value>
            <value>
                <fullName>CONNECT</fullName>
            </value>
            <value>
                <fullName>OPTIONS</fullName>
            </value>
            <value>
                <fullName>TRACE</fullName>
            </value>
            <value>
                <fullName>PATCH</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PT_HttpRequest__mdt/fields/PT_Timeout__c.field-meta.xml
<CustomField>
    <fullName>PT_Timeout__c</fullName>
    <description>Timeout that will be set on the request</description>
    <inlineHelpText>In milliseconds. If left blank it&apos;s set to 10 000ms. Valid range is 1 - 120 000ms</inlineHelpText>
    <label>Timeout</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/HttpRequest/Test/PT_HttpRequestTest.cls
@IsTest
public class PT_HttpRequestTest {
    private static final String HttpMethod_Get = 'GET';
    private static final String HttpMethod_Post = 'POST';
    private static final String EndpointMock = 'ENDPOINT_MOCK';
    private static final Integer TimeoutMock = 1;
    private static final String MetadataNameMock = 'Lorem Ipsum';
    private static final String BodyMock_Query = 'QUERY';
    private static final String BodyMock_Json = 'JSON';

    @IsTest
    static void toRequestNoBody_Test() {
        //Arrange
        PT_HttpRequest__mdt configMdt = getMetadataRecord();
        PT_IHttpRequest ptReq = new PT_HttpRequest(configMdt.DeveloperName);

        //Act
        Test.startTest();
        HttpRequest req = ptReq.toRequest();
        Test.stopTest();

        //Assert
        System.assertEquals(configMdt.PT_Endpoint__c, req.getEndpoint());
        System.assertEquals(configMdt.PT_HttpMethod__c, req.getMethod());
    }

    @IsTest
    static void constructionNoMdtFound_Test() {
        //Arrange
        PT_HttpRequestConfigException expectedException;

        //Act
        Test.startTest();
        try {
            new PT_HttpRequest(MetadataNameMock);
        } catch (PT_HttpRequestConfigException ex) {
            expectedException = ex;
        }
        Test.stopTest();

        //Assert
        System.assertNotEquals(null, expectedException);
        System.assert(expectedException.getMessage().contains(MetadataNameMock));
    }

    @IsTest
    static void queryParamBodyForGetMethod_Test() {
        //Arrange
        PT_IHttpRequestConfig requestConfigMock =
                (PT_IHttpRequestConfig)Test.createStub(
                        PT_IHttpRequestConfig.class,
                        new PT_HttpRequestConfigMock(
                                TimeoutMock,
                                EndpointMock,
                                HttpMethod_Get));

        PT_HttpRequest ptReq = new PT_HttpRequest();
        ptReq.config = requestConfigMock;

        //Act
        Test.startTest();
        ptReq.setBody(new PT_TestRequestBody()); // Check inner class below
        HttpRequest req = ptReq.toRequest();
        Test.stopTest();

        //Assert
        System.assert(req.getEndpoint().contains(BodyMock_Query));
        System.assert(req.getEndpoint().contains(EndpointMock));
        System.assert(String.isEmpty(req.getBody()));
    }

    @IsTest
    static void jsonParamBodyForPostMethod_Test() {
        //Arrange
        PT_IHttpRequestConfig requestConfigMock =
                (PT_IHttpRequestConfig)Test.createStub(
                        PT_IHttpRequestConfig.class,
                        new PT_HttpRequestConfigMock(
                                TimeoutMock,
                                EndpointMock,
                                HttpMethod_Post));

        PT_HttpRequest ptReq = new PT_HttpRequest();
        ptReq.config = requestConfigMock;

        //Act
        Test.startTest();
        ptReq.setBody(new PT_TestRequestBody()); // Check inner class below
        HttpRequest req = ptReq.toRequest();
        Test.stopTest();

        //Assert
        System.assertEquals(BodyMock_Json, req.getBody());
        System.assertEquals(EndpointMock, req.getEndpoint());
        System.assert(!req.getEndpoint().contains(BodyMock_Query));
        System.assert(!req.getEndpoint().contains(BodyMock_Json));
    }

    /*
     * Created to facilitate cross org test success, though still at least
     * one record has to be created. Mocking metadata retrieval is not relevant
     * for performing HttpRequests thus it was not implemented.
     */
    private static PT_HttpRequest__mdt getMetadataRecord() {
        return [
                SELECT Id, DeveloperName, PT_HttpMethod__c, PT_Endpoint__c, PT_Timeout__c
                FROM PT_HttpRequest__mdt
                LIMIT 1
        ];
    }

    private class PT_TestRequestBody implements PT_IRequestBody {
        public String toQueryParams() {
            return BodyMock_Query;
        }

        public String toJsonBody() {
            return BodyMock_Json;
        }
    }
}