force-app/main/default/objects/PT_HttpRequest__mdt/PT_HttpRequest__mdt.object-meta.xml
<CustomObject>
    <label>PT_HttpRequest</label>
    <pluralLabel>PT_HttpRequests</pluralLabel>
</CustomObject>

force-app/main/default/objects/PT_HttpRequest__mdt/fields/PT_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>PT_Endpoint__c</fullName>
    <label>Endpoint</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PT_HttpRequest__mdt/fields/PT_HttpMethod__c.field-meta.xml
<CustomField>
    <fullName>PT_HttpMethod__c</fullName>
    <description>Used to set the HTTP method on the request.</description>
    <label>Http Method</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GET</fullName>
                <default>true</default>
                <label>GET</label>
            </value>
            <value>
                <fullName>POST</fullName>
            </value>
            <value>
                <fullName>PUT</fullName>
            </value>
            <value>
                <fullName>DELETE</fullName>
            </value>
            <value>
                <fullName>HEAD</fullName>
            </value>
            <value>
                <fullName>CONNECT</fullName>
            </value>
            <value>
                <fullName>OPTIONS</fullName>
            </value>
            <value>
                <fullName>TRACE</fullName>
            </value>
            <value>
                <fullName>PATCH</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PT_HttpRequest__mdt/fields/PT_Timeout__c.field-meta.xml
<CustomField>
    <fullName>PT_Timeout__c</fullName>
    <description>Timeout that will be set on the request</description>
    <inlineHelpText>In milliseconds. If left blank it&apos;s set to 10 000ms. Valid range is 1 - 120 000ms</inlineHelpText>
    <label>Timeout</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PT_HttpResponseMock__mdt/PT_HttpResponseMock__mdt.object-meta.xml
<CustomObject>
    <label>PT_HttpResponseMock</label>
    <pluralLabel>PT_HttpResponseMocks</pluralLabel>
</CustomObject>

force-app/main/default/classes/HttpRequest/Test/PT_HttpRequestConfigTest.cls
/*
    Not tested: getActiveMock positive scenario to avoid dependency on actual MDT records
 */

@IsTest
private class PT_HttpRequestConfigTest {
    private final static String MockedDeveloperName = 'ABC';
    private final static String MockedMethod = 'GET';
    private final static String MockedEndpoint = 'https://test.com';
    private final static Decimal MockedTimeout = 10000;

    @IsTest
    static void configNotFoundExceptionThrown_Test() {
        //Arrange
        String fakeName = 'fake_name_to_trigger_exception';
        PT_HttpRequestConfigException expectedException;
        //Act
        try {
            new PT_HttpRequestConfig(fakeName);
        } catch (PT_HttpRequestConfigException ex) {
            expectedException = ex;
        }

        //Assert
        System.assertNotEquals(null, expectedException);
        System.assert(expectedException.getMessage().contains(fakeName));
    }

    @IsTest
    static void getDataBasedOnMetadata_Test() {
        //Arrange
        PT_HttpRequest__mdt configRecord = getMetadataRecord();
        PT_HttpRequestConfig config = new PT_HttpRequestConfig(); //unavailable in business code
        config.record = configRecord; //unavailable in business code

        //Act
        String method = config.getMethod();
        String endpoint = config.getEndpoint();
        Integer timeout = config.getTimeout();

        //Assert
        System.assertEquals(configRecord.PT_HttpMethod__c, method);
        System.assertEquals(configRecord.PT_Endpoint__c, endpoint);
        System.assertEquals(configRecord.PT_Timeout__c, timeout);
    }

    @IsTest
    static void exceptionWhenMockRequestedButThereIsNoMock_Test() {
        //Arrange
        PT_HttpRequestConfigException expectedException;
        PT_HttpRequest__mdt configRecord = getMetadataRecord();
        PT_HttpRequestConfig config = new PT_HttpRequestConfig(); //unavailable in business code
        config.record = configRecord; //unavailable in business code

        //Act
        try {
            config.getActiveMock();
        } catch (PT_HttpRequestConfigException ex) {
            expectedException = ex;
        }

        //Assert
        System.assertNotEquals(null, expectedException);
        System.assert(expectedException.getMessage().contains(MockedDeveloperName));
    }

    @IsTest
    static void statingThereIsNoMockInUnitTestsWhenMockRecordIsPresent_Test() {
        //Arrange
        PT_HttpRequest__mdt configRecord = getMetadataRecord();
        Id val = PT_HttpResponseMock__mdt.SObjectType.getDescribe().getKeyPrefix() + '5500a2r15wqs';
        configRecord.put(PT_HttpRequest__mdt.PT_HttpMethod__c, val);
        PT_HttpRequestConfig config = new PT_HttpRequestConfig(); //unavailable in business code
        config.record = configRecord; //unavailable in business code

        //Act
        Boolean hasActiveMock = config.hasActiveMock();

        //Assert
        System.assert(!hasActiveMock);
    }

    /*
     * Created to facilitate cross-org test execution without dependency on actual configuration
     */
    private static PT_HttpRequest__mdt getMetadataRecord() {

        Map<String, Object> untypedMetadataRecord = new Map<String, Object> {
                PT_HttpRequest__mdt.DeveloperName.getDescribe().name => MockedDeveloperName,
                PT_HttpRequest__mdt.PT_HttpMethod__c.getDescribe().name => MockedMethod,
                PT_HttpRequest__mdt.PT_Endpoint__c.getDescribe().name => MockedEndpoint,
                PT_HttpRequest__mdt.PT_Timeout__c.getDescribe().name => MockedTimeout
        };
        return (PT_HttpRequest__mdt)JSON.deserialize(JSON.serialize(untypedMetadataRecord), PT_HttpRequest__mdt.class);
    }
}